### ISSUE TITLE
Objekte der Klasse Vektor sollten vor Veränderungen geschützt sein.

### ISSUE THREAD

**Issue by wi7e** [tpe-lecture/group-23#5]
Laut JavaDoc: "Objekte dieser Klasse sind immutable. Die Methoden verändern den Zustand des Objektes nicht sondern geben ein neues Objekt zurück."

in eurer aktuellen Implementierung lassen sich Objektattribute jedoch von aussen zugreifen (manipulieren)

**Comment by AdemAlagoez** [comment]
done
